
version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8088:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: mason
      WORDPRESS_DB_PASSWORD: 121234
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./data/wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: mason
      MYSQL_PASSWORD: 121234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data/db:/var/lib/mysql

volumes:
  wordpress:
  db:
